### PR TITLE
Add LTC NB681

### PR DESCRIPTION
**Pull request by dustinlieu**
Dumped using an ST-Link

### CODE REVIEW

**Comment by stroobandt** [comment]
Could this pull request, please, be added to the main branch?
I have an LTC NB681 anxiously awaiting this. Thanks!

**Comment by mannyatico** [comment]
Has anyone tested this? does it work?

**Comment by dustinlieu** [comment]
This is just the stock FW that I backed up. It is not a SonixQMK firmware for this board.

**Comment by TSnatch72** [comment]
Is there any plan to merge this commit? It seem's like there's no reason not to

**Pull request merged**
